### ISSUE TITLE
No empty state for milestones

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#1283] opened 2017-12-18 13:43 UTC
![GitHawk Upload by viktorgardart](https://i.imgur.com/26zwENI.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513546049)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment] 2017-12-18 13:46
Dupe of #1234 :)

**Closed by BasThomas** 2017-12-18 13:46 UTC

**Comment by viktorgardart** [comment] 2017-12-18 14:09
Ooh nice! 😃 love the issue #

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
