### ISSUE TITLE
Expanding and collapsing device info

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#598] opened 2017-10-17 09:53 UTC
Expanding and collapsing device info doesn’t resize back.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2092)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by viktorgardart** [comment] 2017-10-17 09:54
The “bug report dump”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2017-10-17 10:11
Dupe of #371

**Closed by Sherlouk** 2017-10-17 10:11 UTC

**Comment by viktorgardart** [comment] 2017-10-17 10:47
Sorry about that one! Thanks! 👍
