### ISSUE TITLE
Blow away bitmap caches on memory warning

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#992] opened 2017-11-19 17:06 UTC
`NSAttributedStringSizing` should dump it’s cache on memory warning. Only for bitmaps tho.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1197)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment] 2017-11-19 17:13
Duplicate of #677?

**Comment by rnystrom** [comment] 2017-11-19 17:39
Oops ya. Closing that one since this has more detail.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2017-11-19 23:16 UTC
Labels: bug, high
