### ISSUE TITLE
Add support for issue saved replies

### ISSUE THREAD

**Issue by orta** [rnystrom/GitHawk#1394] opened 2018-01-13 12:30 UTC
Is there an api for it? Dunno, but I miss being able to use my issue templates when I manage issues via GitHawk 

Could be scraped if not ;)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment] 2018-01-13 13:27
You mean how issues are prefilled with the template?

If so it's dupe of #404 (No surprising you couldn't find it 😉)

The reason we've not been able to do that super easily is unlike the README which has an endpoint to return it straight up, because of all the possible file names it adds a bit more complexity (could be in .github or root, different capitalisation, with or without extension etc)

Definitely doable with API though!

**Comment by BasThomas** [comment] 2018-01-13 13:27
Nice ninja @Sherlouk 😅

**Comment by orta** [comment] 2018-01-13 15:34
lolz at the #404 dupe

Now  I'm at a computer  - I mean these "saved replies" are the official name

![screen shot 2018-01-13 at 10 34 36 am](https://user-images.githubusercontent.com/49038/34907493-62c1543a-f84d-11e7-9fc6-031fefe92e49.png)

**Comment by Sherlouk** [comment] 2018-01-13 15:43
I think that one is #202 😬 😅

**Comment by rnystrom** [comment] 2018-01-13 16:02
Ya I don’t think there’s an API for this, but been on my TODO to just make a local list of replies that you can select from.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2018-01-13 19:15
Can't see an API either, but I think a local version will be just as valid! Closing this in favour of keeping the discussion in one thread though 😄

**Closed by Sherlouk** 2018-01-13 19:15 UTC

**Comment by orta** [comment] 2018-01-13 19:20
Agree
