### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by iandundas** [rnystrom/GitHawk#1470] opened 2018-01-23 07:58 UTC
I've just downloaded 1.17.0 from the App Store. When I open the app & tap "Sign in with GitHub", the app crashes. 

Let me know if I can provide for info!

**Comment by SD10** [comment] 2018-01-23 08:07
Hey @iandundas, thank you for reporting this 👍 It looks to be a duplicate of #1464

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2018-01-23 13:54
Fixed build is in review right now!

**Closed by rnystrom** 2018-01-23 13:54 UTC
