### ISSUE TITLE
Pin repositories

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#571] opened 2017-10-15 10:47 UTC
I think it would be nice to be able to pin repositories to the home screen so you can easily navigate to them without needing to search for it first

**Comment by rnystrom** [comment] 2017-10-15 13:20
Ya I think a “favorites” tab would be awesome eventually

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment] 2017-10-17 07:29
Dupe of #344

**Closed** 2017-10-17 07:59 UTC
Labels: wishlist
