### ISSUE TITLE
Adding label then refreshing issues doesn’t add label dot

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#722] opened 2017-10-24 13:23 UTC
![GitHawk Upload by Sherlouk](https://i.imgur.com/EUSHySD.jpg)However it does increase the size of the cell.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment] 2017-10-24 13:25
Scrolling back does update the cell tho. Seems like the model is missing labels in its equality check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment] 2017-10-24 15:27
duplicate #715?

**Comment by joerocca** [comment] 2017-10-24 15:31
Fixed in #716

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment] 2017-10-24 17:58
Closing as a dupe of #715

**Closed by heshamsalman** 2017-10-24 17:58 UTC
Labels: bug, high

**Comment by rnystrom** [comment] 2017-10-24 18:33
😍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
