### ISSUE TITLE
Cannot dismiss the action sheet on the repo screen

### ISSUE THREAD

**Issue by ninjaprox** [rnystrom/GitHawk#427] opened 2017-09-25 13:59 UTC
Version 1.10.0 (1900)
Device: iPhone 6s (iOS 10.3.3) 

I'm not sure if it's a bug or feature 😉. The action sheet on the repo screen cannot be dismissed by tapping outside which it's supposed to be. Tapping one of the options will dismiss the action sheet though.

**Comment by rizwankce** [comment] 2017-09-25 14:20
Dupe of #407  - fixed and awaiting release. Sorry for the inconvenience!

**Closed** 2017-09-25 14:26 UTC
