### ISSUE TITLE
Can't interact with the top sections

### ISSUE THREAD

**Issue by wilbertliu** [rnystrom/GitHawk#283] opened 2017-09-05 00:54 UTC
Here I attach the video on what's happening.
[ScreenRecording_09-05-2017 07:44.MP4.zip](https://github.com/rnystrom/GitHawk/files/1275694/ScreenRecording_09-05-2017.07.44.MP4.zip)

Things I can't do :
- Can't see the title of the PR clearly.
- Can't select the affected files on PR.

Hope that's clear enough to address the issue.
Thanks! 🙏🏻

**Comment by rnystrom** [comment] 2017-09-05 01:12
Dupe of #18

**Closed by rnystrom** 2017-09-05 01:12 UTC
