### ISSUE TITLE
MessageViewController.swift line 124

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1429] opened 2018-01-16 22:43 UTC
#### in MessageViewController.layout() -> ()

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5e7ff68cb3c2fa63f93ff4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5e7ff68cb3c2fa63f93ff4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by Sherlouk** [comment] 2018-01-16 22:44
Dupe of #1427

**Closed by Sherlouk** 2018-01-16 22:44 UTC
