### ISSUE TITLE
Ability to select text in a comment?

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1559] opened 2018-02-21 09:26 UTC
I miss this, I often select text to copy, look-up, translate. 

Can it be added?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518753170)
Device: iPhone 6s (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2018-02-21 10:40
Dupe of #609?

**Comment by gingerbeardman** [comment] 2018-02-21 10:41
Yes, dupe.

Shall I close?

**Closed** 2018-02-21 12:13 UTC
