### ISSUE TITLE
Attributed string sizing objects LRU bitmaps

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#991] opened 2017-11-19 17:05 UTC
`NSAttributedStringSizing` should be limited to last 2 recently used but maps. If these strings get stored in a FlatCache, they may hold on to large bitmaps forever. Resign windows create new bitmaps. Could waste tons of memory.

Maybe even last 1 bitmap? 2 would help when frequently resizing, but maybe it’s ok to just blow away the last one.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1197)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment] 2017-11-19 17:12
duplicate of #676?

**Comment by rnystrom** [comment] 2017-11-19 17:39
Rofl I’m losing it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment] 2017-11-22 09:29
Closing as #676 is closed.

**Closed** 2017-11-25 02:18 UTC
Labels: bug, high
