### ISSUE TITLE
Animated GIFs not animated

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#499] opened 2017-10-06 19:09 UTC
If you have a README which contains a GIF which is animated it's not showing the animation / other frames.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorgardart** [comment] 2017-10-06 19:13
@weyert Could you provide an example of a repository with a GIF in the README?

**Comment by weyert** [comment] 2017-10-06 19:36
https://github.com/Ramotion/folding-cell :)

**Comment by Sherlouk** [comment] 2017-10-06 19:56
Dupe of #75? We could quite easily add support for GIFs using FLAnimatedImage which is part of SDWebImage (which we have).

Just need to update to use the right image views 😄

**Comment by rnystrom** [comment] 2017-10-06 22:20
Yup dupe

**Closed by rnystrom** 2017-10-06 22:20 UTC
