### ISSUE TITLE
Runtime warning from Xcode

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#1364] opened 2018-01-06 07:17 UTC
Getting a runtime warning for "UI API called from background thread".

![screen shot 2018-01-06 at 3 12 09 pm](https://user-images.githubusercontent.com/12063704/34637587-7a74a252-f2f4-11e7-8041-3d313cbfbfe0.png)

Exactly from 
https://github.com/rnystrom/GitHawk/blob/master/Classes/Views/Styles.swift#L56

**Comment by BasThomas** [comment] 2018-01-06 07:43
Duplicate of #1225. 😃 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by BasThomas** 2018-01-06 07:43 UTC

**Comment by rizwankce** [comment] 2018-01-06 07:46
@BasThomas oh my bad! Need to catch up with issues before I post new one here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
