### ISSUE TITLE
Show paste menu control after inserting link

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#266] opened 2017-08-28 20:47 UTC
Easier workflow to paste whatever's on the clipboard. Should paste between ( and ), e.g.

```
[google.com(PASTE HERE)
```

**Comment by SD10** [comment] 2018-02-15 06:41
Looks like a duplicate of #1453?

**Comment by BasThomas** [comment] 2018-02-15 07:57
Looks like it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by BasThomas** 2018-02-15 07:57 UTC
Labels: feature, mid
