### ISSUE TITLE
I can’t download files that can’t be displayed as text.

### ISSUE THREAD

**Issue by F4Tornado** [rnystrom/GitHawk#1209] opened 2017-12-09 21:07 UTC
I can’t download files that can’t be displayed as text. I don’t know if this is intended behavior.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512350154)
Device: iPad Mini 2 (iOS 11.0.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment] 2017-12-09 21:17
Dupe of #587 (its expected now, but something we want to keep advancing)

**Closed by rnystrom** 2017-12-09 21:17 UTC
Labels: question
