### ISSUE TITLE
Show difference between team member and contributor review

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1117] opened 2017-11-29 13:59 UTC
Do we have this information from the API or would it require an extra call?

![GitHawk Upload by BasThomas](https://i.imgur.com/8vY03G0.jpg)

![GitHawk Upload by BasThomas](https://i.imgur.com/yxsQf8S.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1511717840)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2017-11-29 14:23
I've had a branch with this work on for absolutely ages, but I didn't like the design of it so I haven't done a PR 😂 

It doesn't need an extra API request, just a new value (author association) in the GQL

Dupe of #153 though

**Closed by Sherlouk** 2017-11-29 14:23 UTC
