### ISSUE TITLE
”edit tags” is visible where im not authorized to edit tags

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#838] opened 2017-11-03 21:33 UTC
![GitHawk Upload by viktorgardart](https://i.imgur.com/Wsmpjpt.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone10,6 (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2017-11-03 21:53
dupe of #712?

**Comment by viktorgardart** [comment] 2017-11-03 22:00
@Sherlouk looks like it, i knew i had seen a issue like it before 😅 but couldn’t find it, closing!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2017-11-03 22:11 UTC

**Comment by viktorgardart** [comment] 2017-11-03 22:16
Wait what, I couldn’t close it either? Shouldn’t I be able to do it? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2017-11-03 22:18
😂 Who knows! You should be able to close your own issues IIRC
