### ISSUE TITLE
Reactions misplaced after sequence of events

### ISSUE THREAD

**Issue by yusuftor** [rnystrom/GitHawk#1560] opened 2018-02-21 09:27 UTC
The reaction part of the cells on comments are misplaced after doing the following:
1. Press on a reaction to see who made it
2. Expand a large comment
3. Go back down to see the original comment with the reaction on it.

See these photos for what I mean:
![GitHawk Upload by yusuftor](https://i.imgur.com/D41boA7.jpg)
![GitHawk Upload by yusuftor](https://i.imgur.com/zNq7lKr.jpg)
![GitHawk Upload by yusuftor](https://i.imgur.com/a7Q5177.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment] 2018-02-21 12:19
dupe of https://github.com/rnystrom/GitHawk/issues/1391 ?

**Closed** 2018-02-21 14:12 UTC
Labels: bug
