### ISSUE TITLE
Add support for users/orgs in search

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1285] opened 2017-12-18 15:25 UTC
Seems to only search repos atm.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513546049)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2017-12-18 15:47
Dupe of #345

**Closed by Sherlouk** 2017-12-18 15:47 UTC
