### ISSUE TITLE
Unable to close action sheet on repo page

### ISSUE THREAD

**Issue by dylanslewis** [rnystrom/GitHawk#411] opened 2017-09-24 09:30 UTC
Steps to reproduce:
- go to repo page
- tap three dots icon

Expected behaviour:
- cancel button allows user to close the action sheet

Actual behaviour:
- action sheet can only be closed by performing an action which takes the user away from the page, limiting user recoverability

![a2496080-3700-411b-a1a7-2bf8ec77aec6](https://user-images.githubusercontent.com/8267782/30781223-06f352ca-a113-11e7-9328-d34ed2bd9697.png)

**Comment by Sherlouk** [comment] 2017-09-24 09:31
Dupe of #407 - fixed upstream awaiting release. Sorry for the inconvenience!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by Sherlouk** 2017-09-24 09:31 UTC
