### ISSUE TITLE
Synchronize bookmarks across devices

### ISSUE THREAD

**Issue by pegasd** [rnystrom/GitHawk#1179] opened 2017-12-04 07:41 UTC
Would love to see this feature implemented. Possibly by storing bookmarks in iCloud and/or other external services (Dropbox?).

**Comment by Sherlouk** [comment] 2017-12-04 08:48
Dupe of #702 

Would definitely be a cool feature, and with built-in APIs such as CloudKit shouldn't be too difficult either!

**Closed by Sherlouk** 2017-12-04 08:48 UTC
