### ISSUE TITLE
Open and Closed/Merged PR Views

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#714] opened 2017-10-23 23:31 UTC
Open PRs are usually what I’m interested in. Digging through the list of PRs to a long-standing open PR isn’t ideal UX.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2017-10-24 00:16
Yes pls. Need some sort of filter control. Maybe part of the search bar? I think you can have selection items. That or a more custom search bar UI with other filters?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment] 2017-10-24 00:44
Something like this?

<img width="377" alt="screen shot 2017-10-23 at 8 42 27 pm" src="https://user-images.githubusercontent.com/3388381/31919776-b8c30b90-b832-11e7-9d50-5543b530dc9e.png">

**Comment by BasThomas** [comment] 2017-10-24 04:11
Yes, let's do this. I think the filter UI would also be a good candidate to try and see if we can maybe move away from long actionsheets: https://github.com/rnystrom/GitHawk/pull/696#discussion_r146396805

**Comment by rizwankce** [comment] 2017-10-24 05:13
I was just searching different approach for our action sheet and came across with filter icon used for the filter.Tweetbot and Skype are using the same. 

Maybe we can have a filter icon, on tap of that show an action sheet with actions like 
 - PR only
 - Issues only
 - Commits only

**Comment by joerocca** [comment] 2017-10-24 05:29
Think this is a duplicate of #287

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment] 2017-10-24 05:32
Seems like it!

**Closed by BasThomas** 2017-10-24 05:32 UTC
Labels: feature, low
