### ISSUE TITLE
Issue and PR lists in repo bottom inset under tabs

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#919] opened 2017-11-10 17:52 UTC
Is this a dupe? I saw another comment about stuff under the tab.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment] 2017-11-10 17:59
Yeah, dupe of #889
#907 is also similar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2017-11-10 17:59 UTC
Labels: bug, high
