### ISSUE TITLE
Canceling bookmark search doesn't reset data

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#733] opened 2017-10-25 13:36 UTC
- I have GitHawk and IGListKit bookmarked
- Type "git"
- Hit "Cancel"
- Only shows GitHawk

Force kill app and restart fixes it

cc @rizwankce

**Comment by rizwankce** [comment] 2017-10-25 14:23
Dupe of #728. Fix is on #729

**Closed** 2017-10-25 14:55 UTC
Labels: bug, high
